import React from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter} from 'react-router-dom';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import AuthProvider from './context/AuthContext.jsx';
import AppRoutes from './routes/AppRoutes.jsx';
import {createApi} from './api/client.js';
import * as constants from '../../shared/constants.js';
import './main.css';
const api=createApi(import.meta.env.VITE_API_BASE_URL),queryClient=new QueryClient();
createRoot(document.getElementById('root')).render(<QueryClientProvider client={queryClient}><BrowserRouter><AuthProvider api={api} queryClient={queryClient} constants={constants}><AppRoutes/></AuthProvider></BrowserRouter></QueryClientProvider>);
