import {Router} from 'express';
import {z} from 'zod';
import {rateLimit} from 'express-rate-limit';
import {authenticate} from '../middlewares/auth.js';
import {requireRole} from '../middlewares/role.js';
import {validate} from '../middlewares/validate.js';
import {success} from '../controllers/auth.controller.js';
import {emptySchema} from '../validators/auth.schema.js';
import {idParams} from '../validators/properties.schema.js';
import * as v from '../validators/finance.schema.js';
import User from '../models/User.js';
import Property from '../models/Property.js';
import Investment from '../models/Investment.js';
import Transaction from '../models/Transaction.js';
import Withdrawal from '../models/Withdrawal.js';
import Settings from '../models/Settings.js';
import {invest,investmentDTO} from '../services/investment.service.js';
import {createWalletService,getWallet} from '../services/wallet.service.js';
import {requestWithdrawal,reviewWithdrawal,withdrawalDTO} from '../services/withdrawal.service.js';
import {previewPayout,executePayout} from '../services/payout.service.js';
import {reviewProperty,changePropertyStatus} from '../services/propertyLifecycle.service.js';
import {portfolioSummary} from '../services/portfolio.service.js';
import {adminStats,updateUser} from '../services/admin.service.js';
import {submitKyc,reviewKyc} from '../services/kyc.service.js';
import {settings,settingsDTO} from '../services/settings.service.js';
import {describeProperty} from '../services/property.service.js';
import {pageDTO,sortSpec,literalSearch,userDTO,transactionDTO} from '../utils/dto.js';
import ApiError from '../utils/ApiError.js';
const feature=(env,key)=>(req,res,next)=>{if(!env[key])throw new ApiError('FEATURE_DISABLED','This feature is disabled');next();};
const range=q=>({...((q.from||q.to)&&{createdAt:{...(q.from&&{$gte:new Date(q.from)}),...(q.to&&{$lt:new Date(q.to)})}})});
async function list(model,filter,q,mapper=x=>x){const [rows,total]=await Promise.all([model.find(filter).sort(sortSpec(q.sort)).skip((q.page-1)*q.limit).limit(q.limit),model.countDocuments(filter)]);return pageDTO(await Promise.all(rows.map(mapper)),total,q);}
export function financeRoutes(env,uploads){
  const r=Router(),auth=authenticate(env),investor=requireRole('INVESTOR'),admin=requireRole('ADMIN'),wallet=createWalletService(env);
  const route=(method,path,guards,schema,fn,code=200,source=method==='get'?'query':'body')=>r[method](path,auth,...guards,validate(schema,source),async(req,res)=>success(res,await fn(req),'Operation completed',code));
  route('get','/wallet',[investor],emptySchema,req=>getWallet(req.user._id));
  route('post','/wallet/topup/order',[investor],v.amountBody,req=>wallet.order(req.user,req.validated.body),201);
  route('post','/wallet/topup/verify',[investor],v.verifyBody,req=>wallet.verify(req.user,req.validated.body));
  route('post','/wallet/withdraw',[investor,feature(env,'WITHDRAWALS_ENABLED')],v.withdrawBody,req=>requestWithdrawal(req.user,req.validated.body),201);
  route('get','/wallet/withdrawals',[investor,feature(env,'WITHDRAWALS_ENABLED')],v.withdrawalQuery,req=>list(Withdrawal,{userId:req.user._id,...(req.validated.query.status&&{status:req.validated.query.status})},req.validated.query,withdrawalDTO),200,'query');
  r.post('/investments',auth,investor,rateLimit({windowMs:60000,limit:60,standardHeaders:'draft-8',legacyHeaders:false,handler:(req,res)=>res.status(429).json({success:false,error:{code:'RATE_LIMITED',message:'Too many investment requests',details:[]}})}),validate(v.investBody),async(req,res)=>{const key=z.uuid().safeParse(req.get('Idempotency-Key'));if(!key.success)throw new ApiError('VALIDATION_ERROR','Idempotency-Key must be a UUID');const result=await invest(req.user,req.validated.body,key.data,env);success(res,result.data,'Investment confirmed',result.replayed?200:201);});
  route('get','/investments/me',[investor],v.investmentQuery,req=>{const q=req.validated.query;return list(Investment,{investorId:req.user._id,...(q.propertyId&&{propertyId:q.propertyId}),...(q.status&&{status:q.status})},q,async i=>{const p=await Property.findById(i.propertyId);return {investment:investmentDTO({...i.toObject(),ownershipPct:i.units/p.totalUnits*100}),property:await describeProperty(p)};});},200,'query');
  route('get','/portfolio/summary',[investor],emptySchema,req=>portfolioSummary(req.user._id));
  route('get','/transactions',[],v.transactionQuery,req=>{const q=req.validated.query;if(q.userId&&req.user.role!=='ADMIN')throw new ApiError('FORBIDDEN','Only admins can select another account');return list(Transaction,{...(req.user.role==='ADMIN'?(q.userId&&{userId:q.userId}):{userId:req.user._id}),...(q.type&&{type:q.type}),...(q.direction&&{direction:q.direction}),...range(q)},q,transactionDTO);},200,'query');
  const id=[admin,validate(idParams,'params')];
  route('post','/properties/:id/approve',id,emptySchema,req=>reviewProperty(req.user,req.params.id,{status:'LIVE'},env));
  route('post','/properties/:id/reject',id,v.rejectBody,req=>reviewProperty(req.user,req.params.id,{status:'REJECTED',...req.validated.body},env));
  route('post','/properties/:id/status',id,v.statusBody,req=>changePropertyStatus(req.params.id,req.validated.body.status));
  route('get','/properties/:id/payout-preview',id,v.previewQuery,req=>previewPayout(req.params.id,req.validated.query.salePrice),200,'query');
  route('post','/properties/:id/sell',id,v.sellBody,req=>executePayout(req.user,req.params.id,req.validated.body,env));
  route('get','/admin/stats',[admin],v.statsQuery,req=>adminStats(req.validated.query,env),200,'query');
  route('get','/admin/properties',[admin],v.adminPropertyQuery,req=>{const q=req.validated.query,f={};for(const k of ['status','brokerId','city'])if(q[k])f[k]=q[k];if(q.search)f.$or=['title','city','address'].map(k=>({[k]:{$regex:literalSearch(q.search),$options:'i'}}));return list(Property,f,q,describeProperty);},200,'query');
  route('get','/admin/users',[admin],v.usersQuery,req=>{const q=req.validated.query,f={};for(const k of ['role','isActive','brokerApproved'])if(q[k]!==undefined)f[k]=q[k];if(q.kycStatus)f['kyc.status']=q.kycStatus;if(q.search)f.$or=['name','email'].map(k=>({[k]:{$regex:literalSearch(q.search),$options:'i'}}));return list(User,f,q,async u=>({...userDTO(u),kyc:{...userDTO(u).kyc,docs:await Promise.all(u.kyc.docs.map(a=>uploads.privateMedia(a))),selfie:u.kyc.selfie?await uploads.privateMedia(u.kyc.selfie):null,reviewedBy:u.kyc.reviewedBy?String(u.kyc.reviewedBy):null,reviewedAt:u.kyc.reviewedAt}}));},200,'query');
  route('patch','/admin/users/:id',id,v.userBody,req=>updateUser(req.user,req.params.id,req.validated.body));
  route('get','/admin/settings',[admin],emptySchema,async()=>settingsDTO(await settings()));
  route('patch','/admin/settings',[admin],v.settingsBody,async req=>{await settings();return settingsDTO(await Settings.findOneAndUpdate({singletonKey:'platform'},{$set:req.validated.body,$inc:{version:1}},{returnDocument:'after',runValidators:true}));});
  route('post','/kyc',[investor,feature(env,'KYC_ENABLED')],v.kycBody,req=>submitKyc(req.user,req.validated.body,uploads),201);
  route('patch','/admin/kyc/:id',[...id,feature(env,'KYC_ENABLED')],v.reviewBody,req=>reviewKyc(req.user,req.params.id,req.validated.body,env));
  route('get','/admin/withdrawals',[admin,feature(env,'WITHDRAWALS_ENABLED')],v.adminWithdrawalQuery,req=>{const q=req.validated.query;return list(Withdrawal,{status:q.status??'PENDING',...(q.userId&&{userId:q.userId}),...range(q)},q,withdrawalDTO);},200,'query');
  route('patch','/admin/withdrawals/:id',[...id,feature(env,'WITHDRAWALS_ENABLED')],v.reviewBody,req=>reviewWithdrawal(req.user,req.params.id,req.validated.body,env));
  return r;
}
