import {z} from 'zod';
import {objectId,pagination,media,brokerQuery} from './properties.schema.js';
import {ROLES,INVESTMENT_STATUS,TRANSACTION_TYPES,KYC_STATUS} from '../../../shared/constants.js';
export const positive=z.number().int().positive().max(Number.MAX_SAFE_INTEGER);
export const rate=z.number().min(0).max(100).refine(v=>/^\d+(\.\d{1,2})?$/.test(String(v)),'At most two decimal places');
const sort=fields=>z.enum(fields.flatMap(f=>[f,`-${f}`])).default('-createdAt');
const search=z.string().trim().min(1).max(100).optional();
const bool=z.enum(['true','false']).transform(v=>v==='true').optional();
const date=z.iso.datetime().optional();
export const dates={from:date,to:date};
export const dateRange=v=>!v.from||!v.to||v.from<v.to;
export const amountBody=z.strictObject({amount:positive});
export const investBody=z.strictObject({propertyId:objectId.transform(v=>v.toLowerCase()),units:positive});
export const investmentQuery=z.strictObject({...pagination,propertyId:objectId.optional(),status:z.enum(Object.values(INVESTMENT_STATUS)).optional(),sort:sort(['createdAt','amount'])});
export const verifyBody=z.strictObject({gatewayOrderId:z.string().min(1).max(100),gatewayPaymentId:z.string().min(1).max(100),mockOrderToken:z.string().min(1).max(2000)});
export const withdrawBody=z.strictObject({amount:positive,bankDetails:z.strictObject({accountHolder:z.string().trim().min(2).max(100),accountNumber:z.string().regex(/^\d{6,20}$/),ifsc:z.string().regex(/^[A-Z]{4}0[A-Z0-9]{6}$/)})});
export const reason=z.string().trim().min(1).max(2000);
export const reviewBody=z.strictObject({status:z.enum(['APPROVED','REJECTED']),reason:reason.optional()}).refine(v=>v.status!=='REJECTED'||!!v.reason,'Rejection requires a reason');
export const rejectBody=z.strictObject({reason});
export const statusBody=z.strictObject({status:z.enum(['HOLDING','CANCELLED'])});
export const previewQuery=z.strictObject({salePrice:z.string().regex(/^\d+$/).transform(Number).pipe(positive)});
export const sellBody=z.strictObject({salePrice:positive,expectedPlatformFeePct:rate});
export const transactionQuery=z.strictObject({...pagination,type:z.enum(Object.values(TRANSACTION_TYPES)).optional(),direction:z.enum(['CREDIT','DEBIT']).optional(),...dates,userId:objectId.optional(),sort:sort(['createdAt','amount'])}).refine(dateRange,'Date range is inverted');
export const withdrawalQuery=z.strictObject({...pagination,status:z.enum(['PENDING','APPROVED','REJECTED']).optional(),sort:sort(['createdAt'])});
export const adminWithdrawalQuery=withdrawalQuery.extend({...dates,userId:objectId.optional(),sort:sort(['createdAt','amount'])}).refine(dateRange,'Date range is inverted');
export const usersQuery=z.strictObject({...pagination,search,role:z.enum(Object.values(ROLES)).optional(),isActive:bool,brokerApproved:bool,kycStatus:z.enum(Object.values(KYC_STATUS)).optional(),sort:sort(['createdAt','name'])});
export const userBody=z.strictObject({isActive:z.boolean().optional(),role:z.enum(Object.values(ROLES)).optional(),brokerApproved:z.boolean().optional()}).refine(v=>Object.keys(v).length>0,'Supply a change');
export const settingsBody=z.strictObject({platformFeePct:rate.optional(),brokerCommissionPct:rate.optional(),maxOwnershipPct:rate.refine(v=>v>0).optional()}).refine(v=>Object.keys(v).length>0,'Supply a change');
export const adminPropertyQuery=brokerQuery.extend({brokerId:objectId.optional()});
export const statsQuery=z.strictObject(dates).refine(dateRange,'Date range is inverted');
export const kycBody=z.strictObject({docs:z.array(media).min(1).max(10),selfie:media});
