import React, { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import useAuth from '../../hooks/useAuth.js';
import { Page, ResourceState, useResource, Pagination, money, date, Status, Notice } from '../auth/DevangUI.jsx';
import { Kpis, Percent, EmptyPagePagination } from '../../components/AppUI.jsx';
export default function HoldingDetail(){
  const {propertyId}=useParams();const {api}=useAuth();const [page,setPage]=useState(1);const portfolio=useResource(()=>api.portfolio.summary(),[propertyId]);const rows=useResource(()=>api.investments.me({propertyId,page,limit:20,sort:'-createdAt'}),[propertyId,page]);
  return <Page title="Your property holding" eyebrow="Investment detail" actions={<Link className="dv-button dv-secondary" to="/investor/portfolio">Portfolio</Link>}><ResourceState resource={portfolio}>{data=>{const holding=data.holdings.find(item=>item.property._id===propertyId);return holding?<><section className="dv-panel"><div className="dv-section-heading"><h2>{holding.property.title}</h2><Status value={holding.status}/></div><p className="dv-muted">{holding.property.city}, {holding.property.state}</p><Link to={`/properties/${propertyId}`}>View property disclosures</Link></section><Kpis items={[["Owned units",holding.units],["Ownership",`${holding.ownershipPct.toFixed(2)}%`],["Principal invested",money(holding.invested)],[holding.status==='ACTIVE'?'Estimated value':holding.status==='REFUNDED'?'Refunded principal':'Realized payout',money(holding.status==='EXITED'?holding.payoutAmount:holding.estimatedValue)],["Return",<Percent value={holding.roiPct}/>]]}/><Notice warning={holding.status==='ACTIVE'}>{holding.status==='ACTIVE'?'Current value uses the appreciation assumption and elapsed time. It is not a cash balance or a guaranteed return.':holding.status==='REFUNDED'?'The property was cancelled and your principal was refunded to your wallet.':'This property was sold. The recorded payout is realized and appears in your wallet ledger.'}</Notice></>:<Notice warning>No holding for this property was found in your account.</Notice>;}}</ResourceState><section className="dv-panel"><h2>Investment history</h2><ResourceState resource={rows} emptyMessage="No investment records for this property.">{data=><><div className="dv-table-wrap" role="region" aria-label="Investment history" tabIndex={0}><table className="dv-table"><thead><tr>{['Date','Units','Amount','Status','Payout'].map(label=><th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{data.items.map(({investment})=><tr key={investment._id}><td>{date(investment.createdAt)}</td><td>{investment.units}</td><td>{money(investment.amount)}</td><td><Status value={investment.status}/></td><td>{money(investment.payoutAmount)}</td></tr>)}</tbody></table></div><Pagination data={data} page={page} onPage={setPage}/></>}</ResourceState><EmptyPagePagination resource={rows} page={page} onPage={setPage}/></section></Page>;
}
