import React, { useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import useAuth from '../../hooks/useAuth.js';
import { Page, Field, ErrorNotice, Notice, ResourceState, useResource, useAction, Confirm, money, Funding } from '../auth/DevangUI.jsx';
import { parsePositiveInteger } from '../../features/broker/money.mjs';
import { createInvestmentIntent } from './investmentIntent.mjs';
import '../../components/App.css';
export default function InvestCheckout(){
  const {id}=useParams();const {api,user,features,featuresLoading}=useAuth();const property=useResource(()=>api.properties.detail(id),[id]);const wallet=useResource(()=>api.wallet.get());const portfolio=useResource(()=>api.portfolio.summary());const action=useAction();
  const [unitsText,setUnitsText]=useState('');const [terms,setTerms]=useState(false);const [confirm,setConfirm]=useState(false);const [uncertain,setUncertain]=useState(false);const [result,setResult]=useState(null);const intent=useRef(createInvestmentIntent());
  const saved=property.data;const holding=portfolio.data?.holdings.find(item=>item.property._id===id && item.status==='ACTIVE');const owned=holding?.units??0;
  let units=0,amount=0,inputError=null;
  try{if(unitsText){units=parsePositiveInteger(unitsText,'Units');if(saved?.unitPrice){const value=BigInt(units)*BigInt(saved.unitPrice);if(value>BigInt(Number.MAX_SAFE_INTEGER))throw new Error('Purchase amount exceeds the safe limit.');amount=Number(value);}}}catch(failure){inputError=failure.message;}
  const maximum=saved?Math.max(0,Math.min(saved.remainingUnits,features.ownershipCap&&saved.maxUnitsPerInvestor!=null? saved.maxUnitsPerInvestor-owned:saved.remainingUnits)):0;
  const estimate=amount&&saved?.holdingPeriodMonths?Math.round(amount*Math.pow(1+(saved.expectedAppreciationPct??0)/100,saved.holdingPeriodMonths/12)):0;
  const shortfall=Math.max(0,amount-(wallet.data?.availableBalance??0));const kycBlocked=features.kyc&&user.kyc?.status!=='APPROVED';
  const valid=!featuresLoading&&!property.loading&&!wallet.loading&&!portfolio.loading&&!property.error&&!wallet.error&&!portfolio.error&&saved?.status==='LIVE'&&units>0&&!inputError&&units>=saved.minUnits&&units<=maximum&&!shortfall&&!kycBlocked&&terms;
  async function purchase(){
    if(!valid&&!uncertain)return;
    action.run(async()=>{
      const current=intent.current.prepare({propertyId:id,units});
      try{const committed=await api.investments.create(current.body,current.key);intent.current.settle();return committed;}
      catch(error){intent.current.settle(error);if(error.status>=400&&error.status<500){setConfirm(false);property.reload();wallet.reload();portfolio.reload();}throw error;}
    },committed=>{setResult(committed);setUncertain(false);setConfirm(false);wallet.reload();portfolio.reload();property.reload();});
  }
  // Action errors settle definite business failures, while network/5xx retain the intent.
  const networkUncertain=!!action.error&&!!intent.current.current();
  function review(){setUncertain(networkUncertain);setConfirm(true);}
  return <Page title="Confirm your property units" eyebrow="Investment checkout" actions={<Link className="dv-button dv-secondary" to={`/properties/${id}`}>Property details</Link>}>
    {result?<section className="dv-panel dv-success-panel"><h2>Your ownership is recorded</h2><p>The server confirmed {result.investment.units} units for {money(result.investment.amount)}.</p><dl className="dv-dl"><div><dt>Ownership</dt><dd>{result.investment.ownershipPct.toFixed(2)}%</dd></div><div><dt>Wallet balance after purchase</dt><dd>{money(result.walletBalance)}</dd></div></dl><div className="dv-actions" style={{marginTop:24}}><Link className="dv-button" to={`/investor/portfolio/${id}`}>View your holding</Link><Link className="dv-button dv-secondary" to="/investor/wallet">View ledger</Link></div></section>:<>
    <ErrorNotice error={action.error}/>{networkUncertain&&<Notice warning>The purchase outcome is unconfirmed. Retry the same units with the same request key to recover the result. Do not start another purchase until this request is resolved.</Notice>}
    <ResourceState resource={property}>{item=><div className="dv-two-col"><section className="dv-panel"><h2>{item.title}</h2><p className="dv-muted">{item.city}, {item.state}</p><Funding property={item}/><Field label="Units to purchase" value={unitsText} onChange={event=>setUnitsText(event.target.value)} inputMode="numeric" disabled={action.pending||networkUncertain} error={inputError} help={`Minimum ${item.minUnits}; available purchase maximum ${maximum}. You currently own ${owned} active units.`}/>{features.ownershipCap&&<p className="dv-small">The server also applies the current platform ownership cap. A displayed availability maximum is not a reservation.</p>}{kycBlocked&&<Notice warning>Your dummy KYC must be approved before purchasing. <Link to="/investor/kyc">View KYC</Link></Notice>}{units>0&&units<item.minUnits&&<Notice warning>Choose at least {item.minUnits} units.</Notice>}{units>maximum&&<Notice warning>The requested units exceed current availability or the property ownership limit.</Notice>}{item.status!=='LIVE'&&<Notice warning>This property is currently unavailable for new purchases.</Notice>}<label className="dv-checkbox"><input type="checkbox" checked={terms} onChange={event=>setTerms(event.target.checked)} disabled={action.pending||networkUncertain}/><span>I have read the property disclosures and understand that returns are estimates, losses are possible, and all payments in this academic project are simulated.</span></label><button className="dv-button" disabled={action.pending||(!valid&&!networkUncertain)} onClick={review}>{networkUncertain?'Retry same purchase':'Review purchase'}</button></section><aside className="dv-panel dv-money-panel"><p className="dv-kicker">Purchase summary</p><dl className="dv-dl"><div><dt>Unit price</dt><dd>{money(item.unitPrice)}</dd></div><div><dt>Units</dt><dd>{units||'—'}</dd></div><div><dt>Provisional principal</dt><dd>{money(amount)}</dd></div><div><dt>Provisional ownership</dt><dd>{item.totalUnits?`${(units/item.totalUnits*100).toFixed(2)}%`:'—'}</dd></div><div><dt>Estimated value after {item.holdingPeriodMonths} months</dt><dd>{Number.isSafeInteger(estimate)?money(estimate):'Outside supported display range'}</dd></div><div><dt>Annual appreciation assumption</dt><dd>{item.expectedAppreciationPct}%</dd></div></dl><ResourceState resource={wallet}>{data=><><dl className="dv-dl" style={{marginTop:24}}><div><dt>Available wallet</dt><dd>{money(data.availableBalance)}</dd></div><div><dt>Reserved for withdrawals</dt><dd>{money(data.reservedBalance)}</dd></div></dl>{shortfall>0&&<Notice warning>You need {money(shortfall)} more simulated balance. <Link to="/investor/wallet">Add test funds</Link></Notice>}</>}</ResourceState><ResourceState resource={portfolio}>{()=> <p className="dv-small" style={{marginTop:24}}>The server validates current ownership, balance and remaining units atomically. The final confirmed principal appears after purchase.</p>}</ResourceState></aside></div>}</ResourceState>
    <Confirm open={confirm} title={networkUncertain?'Recover this purchase?':'Confirm property purchase?'} confirmLabel={networkUncertain?'Retry same purchase':'Confirm purchase'} pending={action.pending} onCancel={()=>setConfirm(false)} onConfirm={purchase}><p><strong>{saved?.title}</strong></p><dl className="dv-dl"><div><dt>Units</dt><dd>{units}</dd></div><div><dt>Provisional principal</dt><dd>{money(amount)}</dd></div></dl><p style={{marginTop:24}}>A successful confirmation debits your simulated wallet and records your units together. The same request key is retained across uncertain retries.</p><ErrorNotice error={action.error}/></Confirm>
    </>}
  </Page>;
}
