import React from 'react';
import { Link } from 'react-router-dom';
import useAuth from '../../hooks/useAuth.js';
import { Page, ResourceState, useResource, money, Notice } from '../auth/DevangUI.jsx';
import { Kpis, Percent, Allocation, LedgerTable, PropertiesGrid } from '../../components/AppUI.jsx';
export default function InvestorDashboard(){
  const {api,user,features}=useAuth();const portfolio=useResource(()=>api.portfolio.summary());const ledger=useResource(()=>api.transactions.list({page:1,limit:5,sort:'-createdAt'}));const suggestions=useResource(()=>api.properties.list({status:'LIVE',page:1,limit:3,sort:'-createdAt'}));
  return <Page title={`Welcome, ${user?.name?.split(' ')[0]||'investor'}`} eyebrow="Investor workspace" actions={<Link className="dv-button" to="/properties">Explore properties</Link>}>{features.kyc && user?.kyc?.status!=='APPROVED'&&<Notice warning>Complete dummy KYC before making a purchase. <Link className="dv-gate-link" to="/investor/kyc">View your KYC status</Link></Notice>}<ResourceState resource={portfolio}>{data=><><Kpis items={[["Total principal invested",money(data.totalInvested)],["Portfolio value",money(data.currentValue)],["Realized payouts",money(data.totalPayouts)],["Overall return",<Percent value={data.overallRoiPct}/>],["Available wallet",money(data.wallet.availableBalance)]]}/><div className="dv-two-col"><section className="dv-panel"><div className="dv-section-heading"><h2>Your ownership journey</h2><Link to="/investor/portfolio">View portfolio</Link></div>{data.holdings.length?data.holdings.slice(0,5).map(holding=><article className="dv-summary-link" key={holding.property._id}><div><Link className="dv-property-name" to={`/investor/portfolio/${holding.property._id}`}>{holding.property.title}</Link><small>{holding.units} units · {holding.ownershipPct.toFixed(2)}% ownership</small></div><div><strong>{money(holding.status==='EXITED'?holding.payoutAmount:holding.estimatedValue)}</strong><p className="dv-small">{holding.status==='ACTIVE'?'Estimated value':holding.status==='REFUNDED'?'Refunded principal':'Realized payout'}</p></div></article>):<div className="dv-empty"><h2>Your portfolio starts with one property</h2><p>Read a listing's disclosures and choose your first units.</p><Link className="dv-button" to="/properties">Browse properties</Link></div>}<p className="dv-small" style={{marginTop:20}}>Portfolio value includes active estimates, realized sales and refunds. Payouts are historical totals, not an additional active holding.</p></section><aside className="dv-panel"><h2>Active principal allocation</h2><Allocation items={data.allocation}/></aside></div></>}</ResourceState><section className="dv-panel"><div className="dv-section-heading"><h2>Recent ledger activity</h2><Link to="/investor/wallet">View wallet & ledger</Link></div><ResourceState resource={ledger} emptyMessage="No transactions yet. Your simulated wallet and property activity will appear here.">{data=><LedgerTable data={data}/>}</ResourceState></section><section className="dv-section"><div className="dv-section-heading"><h2>Live listings to explore</h2><Link to="/properties">View all</Link></div><ResourceState resource={suggestions} emptyMessage="No live listings are currently available.">{data=><PropertiesGrid items={data.items}/>}</ResourceState></section></Page>;
}
