import React, { useState } from 'react';
import useAuth from '../../hooks/useAuth.js';
import { Page, Field, FeatureGate, Notice, ErrorNotice, Status, useAction, Confirm } from '../auth/DevangUI.jsx';
import '../../components/App.css';
export default function Kyc(){
  const {api,user,refreshUser}=useAuth();const action=useAction();const [docs,setDocs]=useState([]);const [selfie,setSelfie]=useState(null);const [confirm,setConfirm]=useState(false);const [done,setDone]=useState(false);const locked=['PENDING','APPROVED'].includes(user?.kyc?.status);
  function upload(event,kind){const files=Array.from(event.target.files??[]);event.target.value='';action.run(async()=>{const media=[];for(const file of files){const allowed=kind==='selfie'?['image/jpeg','image/png','image/webp']:['image/jpeg','image/png','image/webp','application/pdf'];if(!allowed.includes(file.type))throw new Error('Use supported JPG, PNG, WEBP or PDF dummy files; a selfie must be an image.');if(file.size>5*1024*1024)throw new Error('Each dummy file must be no larger than 5 MB.');media.push(await api.uploads.create(file,'kyc'));}return media;},media=>{if(kind==='selfie')setSelfie(media[0]??null);else setDocs(previous=>[...previous,...media]);});}
  function submit(){action.run(async()=>{const result=await api.kyc.submit({docs,selfie});await refreshUser();return result;},()=>{setDone(true);setConfirm(false);});}
  return <Page title="Dummy identity review" eyebrow="Investor KYC"><FeatureGate feature="kyc"><Notice warning>Use fictional documents and a dummy image only. Never upload real identification, identity numbers or a real personal selfie.</Notice><section className="dv-panel"><div className="dv-section-heading"><h2>Your review status</h2><Status value={user?.kyc?.status}/></div>{user?.kyc?.reason&&<Notice warning>Administrator feedback: {user.kyc.reason}</Notice>}{done&&<Notice>Your dummy documents were submitted for review.</Notice>}<button className="dv-button dv-secondary" disabled={action.pending} onClick={()=>action.run(refreshUser)}>Refresh KYC status</button></section><ErrorNotice error={action.error}/>{locked?<Notice>{user.kyc.status==='APPROVED'?'Your dummy KYC is approved. You can invest when the other purchase requirements are met.':'Your dummy KYC is awaiting administrator review. You cannot resubmit until a decision is made.'}</Notice>:<section className="dv-panel"><h2>Prepare a dummy submission</h2><div className="dv-form"><Field label="Dummy identity documents" type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" disabled={action.pending} onChange={event=>upload(event,'docs')} help="At least one dummy image or PDF, maximum 5 MB each."/>{docs.map((media,index)=><div key={media.publicId} className="dv-doc-preview"><a href={media.url} target="_blank" rel="noreferrer">{media.name}</a> <button className="dv-text" disabled={action.pending} onClick={()=>setDocs(previous=>previous.filter((_,position)=>position!==index))}>Remove dummy document</button></div>)}<Field label="Dummy selfie image" type="file" accept="image/jpeg,image/png,image/webp" disabled={action.pending} onChange={event=>upload(event,'selfie')} help="A dummy JPG, PNG or WEBP image, maximum 5 MB."/>{selfie&&<div className="dv-doc-preview"><img src={selfie.url} alt="Uploaded dummy selfie"/><a href={selfie.url} target="_blank" rel="noreferrer">{selfie.name}</a></div>}<button className="dv-button" disabled={action.pending||!docs.length||!selfie} onClick={()=>setConfirm(true)}>{action.pending?'Processing…':'Review dummy submission'}</button></div></section>}<Confirm open={confirm} title="Submit dummy KYC for review?" pending={action.pending} confirmLabel="Submit dummy documents" onCancel={()=>setConfirm(false)} onConfirm={submit}><p>You are submitting {docs.length} dummy documents and a dummy selfie image for private administrator review.</p><p>Confirm that none of these files contain real identity information.</p><ErrorNotice error={action.error}/></Confirm></FeatureGate></Page>;
}
