import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import useAuth from '../../hooks/useAuth.js';
import { Page, Field, ResourceState, useResource, money, Status, enumValues, humanize } from '../auth/DevangUI.jsx';
import { Kpis, Percent, Allocation } from '../../components/AppUI.jsx';
export default function Portfolio(){
  const {api,constants}=useAuth();const resource=useResource(()=>api.portfolio.summary());const [status,setStatus]=useState('');
  return <Page title="Your property portfolio" eyebrow="Ownership & outcomes" actions={<Link className="dv-button" to="/properties">Explore properties</Link>}><p className="dv-portfolio-intro">Active values are projections. Completed sales show realized payouts, and cancelled properties show returned principal.</p><ResourceState resource={resource}>{data=><><Kpis items={[["Total invested",money(data.totalInvested)],["Portfolio value",money(data.currentValue)],["Realized payouts",money(data.totalPayouts)],["Overall return",<Percent value={data.overallRoiPct}/>]]}/><div className="dv-two-col"><section className="dv-panel"><div className="dv-section-heading"><h2>Property holdings</h2><Field label="Investment status"><select value={status} onChange={event=>setStatus(event.target.value)}><option value="">All holdings</option>{enumValues(constants.INVESTMENT_STATUS).map(value=><option key={value} value={value}>{humanize(value)}</option>)}</select></Field></div>{data.holdings.filter(item=>!status||item.status===status).length?<div className="dv-table-wrap" role="region" aria-label="Property holdings" tabIndex={0}><table className="dv-table"><thead><tr>{['Property','Status','Units','Ownership','Invested','Value / outcome','Return'].map(label=><th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{data.holdings.filter(item=>!status||item.status===status).map(holding=><tr key={holding.property._id}><td><Link className="dv-property-name" to={`/investor/portfolio/${holding.property._id}`}>{holding.property.title}</Link></td><td><Status value={holding.status}/></td><td>{holding.units}</td><td>{holding.ownershipPct.toFixed(2)}%</td><td>{money(holding.invested)}</td><td>{money(holding.status==='EXITED'?holding.payoutAmount:holding.estimatedValue)}<br/><small>{holding.status==='ACTIVE'?'Estimate':holding.status==='REFUNDED'?'Refunded':'Realized'}</small></td><td><Percent value={holding.roiPct}/></td></tr>)}</tbody></table></div>:<div className="dv-empty"><h2>No holdings in this view</h2><p>Change the status filter or browse available properties.</p><Link to="/properties">Browse properties</Link></div>}</section><aside className="dv-panel"><h2>Active investment allocation</h2><Allocation items={data.allocation}/></aside></div></>}</ResourceState></Page>;
}
