import React, { useState } from 'react';
import useAuth from '../../hooks/useAuth.js';
import { Page, Field, Form, Notice, ErrorNotice, ResourceState, useResource, useAction, FeatureGate, Confirm, Pagination, money, date, Status, enumValues, humanize, validationError } from '../auth/DevangUI.jsx';
import { Kpis, LedgerTable, EmptyPagePagination } from '../../components/AppUI.jsx';
import { parseRupees } from '../../features/broker/money.mjs';
export default function Wallet(){
  const {api,constants,features}=useAuth();const wallet=useResource(()=>api.wallet.get());const action=useAction();const [message,setMessage]=useState('');
  const [amount,setAmount]=useState('');const [order,setOrder]=useState(null);const [topupConfirm,setTopupConfirm]=useState(false);const [verificationUnresolved,setVerificationUnresolved]=useState(false);
  const [withdrawal,setWithdrawal]=useState(null);const [page,setPage]=useState(1);const [filters,setFilters]=useState({sort:'-createdAt'});const [filterError,setFilterError]=useState(null);const [historyPage,setHistoryPage]=useState(1);const [historyStatus,setHistoryStatus]=useState('');
  const ledger=useResource(()=>api.transactions.list({page,limit:20,...filters}),[page,filters]);
  const history=useResource(()=>api.wallet.withdrawals({page:historyPage,limit:10,sort:'-createdAt',...(historyStatus?{status:historyStatus}:{})}),[historyPage,historyStatus],!!features.withdrawals);
  function refresh(){wallet.reload();ledger.reload();history.reload();}
  function createOrder(event){event.preventDefault();setMessage('');action.run(()=>{const parsed=parseRupees(amount);if(parsed<=0)throw validationError('amount','Enter a positive amount.');return api.wallet.order({amount:parsed});},setOrder);}
  function verify(){setVerificationUnresolved(true);action.run(async()=>{try{return await api.wallet.verify({gatewayOrderId:order.gatewayOrderId,gatewayPaymentId:order.checkout.gatewayPaymentId,mockOrderToken:order.checkout.mockOrderToken});}catch(error){if(error.status>=400&&error.status<500)setVerificationUnresolved(false);throw error;}},()=>{setVerificationUnresolved(false);setOrder(null);setAmount('');setTopupConfirm(false);setMessage('Your test top-up was verified and credited to the simulated wallet.');refresh();});}
  function prepareWithdrawal(event){event.preventDefault();action.setError(null);setMessage('');try{const form=new FormData(event.currentTarget);const parsed=parseRupees(form.get('withdrawalAmount'));if(parsed<=0)throw validationError('withdrawalAmount','Enter a positive withdrawal amount.');if(parsed>(wallet.data?.availableBalance??0))throw validationError('withdrawalAmount','The request exceeds your available wallet balance.');setWithdrawal({amount:parsed,bankDetails:{accountHolder:form.get('accountHolder').trim(),accountNumber:form.get('accountNumber').trim(),ifsc:form.get('ifsc').trim().toUpperCase()}});}catch(error){action.setError(error);}}
  function withdraw(){action.run(()=>api.wallet.withdraw(withdrawal),()=>{setWithdrawal(null);setMessage('Withdrawal requested. The amount is reserved until administrator review; no debit has occurred yet.');refresh();});}
  function applyFilters(event){event.preventDefault();setFilterError(null);try{const values=Object.fromEntries(new FormData(event.currentTarget));const query={};for(const [key,value] of Object.entries(values))if(value){query[key]=['from','to'].includes(key)?new Date(value).toISOString():value;}if(query.from&&query.to&&query.from>=query.to)throw validationError('to','The end must be later than the start.');setFilters(query);setPage(1);}catch(error){setFilterError(error);}}
  const duplicate=action.error?.code==='DUPLICATE_PAYMENT';
  return <Page title="Wallet & ledger" eyebrow="Simulated funds"><Notice warning>Mock payment — no real money. Withdrawals use dummy bank details and simulated processing.</Notice><ErrorNotice error={action.error}/>{message&&<Notice>{message}</Notice>}<ResourceState resource={wallet}>{data=><Kpis items={[["Wallet balance",money(data.balance)],["Reserved for withdrawals",money(data.reservedBalance)],["Available balance",money(data.availableBalance)]]}/>}</ResourceState><div className="dv-two-col"><section className="dv-panel"><h2>Add test funds</h2><p className="dv-small">Creating an order does not add balance. Confirm and verify its signed test proof to credit the wallet.</p><Form error={action.error} className="dv-form" onSubmit={createOrder}><Field label="Test top-up amount (₹)" name="amount" value={amount} onChange={event=>setAmount(event.target.value)} inputMode="decimal" required disabled={action.pending||!!order}/><button className="dv-button" disabled={action.pending||!!order||!amount}>{action.pending?'Processing…':'Create test top-up order'}</button></Form>{order&&<div className="dv-topup-proof"><p><strong>{money(order.amount)} · {order.provider} payment</strong></p><small>Order {order.gatewayOrderId}</small>{order.provider==='mock'?<><p style={{marginTop:16}}>The server has prepared a signed test payment. Confirm to verify it and credit the simulated wallet.</p>{duplicate?<Notice warning>This payment has already been recorded. Refresh the ledger before starting another top-up.</Notice>:<button className="dv-button" disabled={action.pending} onClick={()=>setTopupConfirm(true)}>Confirm mock payment</button>}{duplicate&&<button className="dv-button dv-secondary" disabled={action.pending} onClick={()=>{setOrder(null);setTopupConfirm(false);action.setError(null);refresh();}}>Refresh wallet & close order</button>}</>:<Notice warning>This frontend currently supports the signed mock checkout only. The configured provider cannot be confirmed here; no balance has been credited.</Notice>}{verificationUnresolved&&!action.pending&&<Notice warning>The verification outcome is unconfirmed. Keep this order and retry its same signed proof; do not start another top-up until resolved.</Notice>}{!verificationUnresolved&&!action.pending&&<button className="dv-text" onClick={()=>{setOrder(null);setTopupConfirm(false);action.setError(null);}}>Discard unverified order</button>}</div>}</section>
    <section className="dv-panel"><FeatureGate feature="withdrawals"><h2>Request a simulated withdrawal</h2><p className="dv-small">A request reserves available funds. An administrator approves the debit or rejects and releases the reservation.</p><Form error={action.error} className="dv-form" onSubmit={prepareWithdrawal}><Field label="Withdrawal amount (₹)" name="withdrawalAmount" required inputMode="decimal" disabled={action.pending}/><Field label="Dummy account holder" name="accountHolder" required maxLength={100} disabled={action.pending} help="Use a fictional name; do not enter real bank details."/><Field label="Dummy account number" name="accountNumber" required inputMode="numeric" pattern="[0-9]{9,18}" disabled={action.pending}/><Field label="Dummy IFSC" name="ifsc" required maxLength={11} pattern="[A-Za-z]{4}0[A-Za-z0-9]{6}" disabled={action.pending}/><button className="dv-button dv-secondary" disabled={action.pending||wallet.loading||!wallet.data||!!wallet.error}>Review withdrawal</button></Form></FeatureGate></section></div>
    <section className="dv-panel"><h2>Transaction ledger</h2><p className="dv-small">Append-only records of confirmed money movements. End date filters are exclusive.</p><ErrorNotice error={filterError}/><Form error={filterError} className="dv-filter-grid" onSubmit={applyFilters}><Field label="Transaction type" name="type"><select defaultValue=""><option value="">All types</option>{enumValues(constants.TRANSACTION_TYPES).map(value=><option key={value} value={value}>{humanize(value)}</option>)}</select></Field><Field label="Direction" name="direction"><select defaultValue=""><option value="">Credit & debit</option>{enumValues(constants.TRANSACTION_DIRECTIONS).map(value=><option key={value} value={value}>{humanize(value)}</option>)}</select></Field><Field label="From (inclusive)" name="from" type="datetime-local"/><Field label="To (exclusive)" name="to" type="datetime-local"/><Field label="Sort" name="sort"><select defaultValue="-createdAt"><option value="-createdAt">Newest first</option><option value="createdAt">Oldest first</option><option value="-amount">Amount: high to low</option><option value="amount">Amount: low to high</option></select></Field><button className="dv-button dv-secondary">Apply ledger filters</button></Form><div style={{marginTop:24}}><ResourceState resource={ledger} emptyMessage="No ledger records match this filter.">{data=><LedgerTable data={data} page={page} onPage={setPage}/>}</ResourceState><EmptyPagePagination resource={ledger} page={page} onPage={setPage}/></div></section>
    <section className="dv-panel"><FeatureGate feature="withdrawals"><div className="dv-section-heading"><h2>Withdrawal requests</h2><Field label="Withdrawal status"><select value={historyStatus} onChange={event=>{setHistoryStatus(event.target.value);setHistoryPage(1);}}><option value="">All statuses</option>{enumValues(constants.WITHDRAWAL_STATUS).map(value=><option key={value} value={value}>{humanize(value)}</option>)}</select></Field></div><ResourceState resource={history} emptyMessage="No withdrawal requests yet.">{data=><><div className="dv-table-wrap" role="region" aria-label="Your withdrawal requests" tabIndex={0}><table className="dv-table"><thead><tr>{['Requested','Amount','Status','Account','Review reason'].map(label=><th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{data.items.map(item=><tr key={item._id}><td>{date(item.createdAt)}</td><td>{money(item.amount)}</td><td><Status value={item.status}/></td><td>•••• {item.bankDetails.accountNumber.slice(-4)}</td><td>{item.reason||'—'}</td></tr>)}</tbody></table></div><Pagination data={data} page={historyPage} onPage={setHistoryPage}/></>}</ResourceState><EmptyPagePagination resource={history} page={historyPage} onPage={setHistoryPage}/></FeatureGate></section>
    <Confirm open={topupConfirm&&!duplicate} title="Confirm mock top-up?" confirmLabel="Verify test payment" pending={action.pending} onCancel={()=>setTopupConfirm(false)} onConfirm={verify}><p>Verify the signed server order for <strong>{money(order?.amount)}</strong>. No real money is involved.</p><ErrorNotice error={action.error}/></Confirm><Confirm open={!!withdrawal} title="Request simulated withdrawal?" confirmLabel="Request withdrawal" pending={action.pending} onCancel={()=>setWithdrawal(null)} onConfirm={withdraw}><p>Reserve <strong>{money(withdrawal?.amount)}</strong> for dummy bank account ending <strong>{withdrawal?.bankDetails.accountNumber.slice(-4)}</strong>.</p><p>This does not immediately debit the wallet. Administrator review is required.</p><ErrorNotice error={action.error}/></Confirm>
  </Page>;
}
