import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import useAuth from '../../hooks/useAuth.js';
import { Page, Form, Field, ErrorNotice, ResourceState, useResource, money, humanize } from '../auth/DevangUI.jsx';
import { Kpis } from '../../components/AppUI.jsx';
import FundingChart from '../broker/FundingChart.jsx';
export default function AdminDashboard(){
  const {api,features}=useAuth();const [range,setRange]=useState({});const [error,setError]=useState(null);const resource=useResource(()=>api.admin.stats(range),[range]);
  function apply(event){event.preventDefault();setError(null);try{const values=Object.fromEntries(new FormData(event.currentTarget));const next={};for(const [key,value] of Object.entries(values))if(value)next[key]=new Date(value).toISOString();if(next.from&&next.to&&next.from>=next.to)throw new Error('The end of the range must be later than its start.');setRange(next);}catch(failure){setError(failure);}}
  return <Page title="Platform overview" eyebrow="Administrator workspace"><ErrorNotice error={error}/><Form className="dv-toolbar" onSubmit={apply}><Field label="Chart range from" name="from" type="datetime-local"/><Field label="Chart range to (exclusive)" name="to" type="datetime-local"/><button className="dv-button dv-secondary">Apply chart range</button></Form><ResourceState resource={resource}>{data=><><Kpis items={[["Assets under management",money(data.aum)],["Accounts",Object.values(data.usersByRole).reduce((total,count)=>total+count,0)],["Live properties",data.liveProperties],["Funds raised this month",money(data.fundsRaisedThisMonth)],["Platform fees earned",money(data.platformFeesEarned)]]}/><div className="dv-two-col"><section className="dv-panel"><h2>Capital raised over time</h2><FundingChart series={[{propertyId:'platform',points:data.fundsRaisedSeries}]}/></section><section className="dv-panel"><h2>Review queues</h2>{[['Properties',data.approvalQueue.properties,'/admin/properties?status=PENDING_APPROVAL',true],['Broker approvals',data.approvalQueue.brokers,'/admin/users?role=BROKER&brokerApproved=false',true],['Dummy KYC',data.approvalQueue.kyc,'/admin/kyc',features.kyc],['Withdrawals',data.approvalQueue.withdrawals,'/admin/withdrawals',features.withdrawals]].map(([label,count,to,enabled])=><div className="dv-summary-link" key={label}>{enabled?<Link to={to}>{label}</Link>:<span>{label} · unavailable</span>}<strong className="dv-count">{count}</strong></div>)}</section></div><div className="dv-two-col"><section className="dv-panel"><h2>Properties by lifecycle</h2><ul className="dv-chart-counts">{data.propertiesByStatus.map(item=><li key={item.status}><span>{humanize(item.status)}</span><strong>{item.count}</strong></li>)}</ul></section><section className="dv-panel"><h2>Accounts by role</h2><ul className="dv-chart-counts">{Object.entries(data.usersByRole).map(([role,count])=><li key={role}><span>{humanize(role)}</span><strong>{count}</strong></li>)}</ul></section></div></>}</ResourceState></Page>;
}
