import React, { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import useAuth from '../../hooks/useAuth.js';
import { Page, Field, Form, ErrorNotice, Notice, ResourceState, useResource, useAction, Confirm, Status, Pagination, Funding, money, enumValues, humanize, validationError } from '../auth/DevangUI.jsx';
import { EmptyPagePagination } from '../../components/AppUI.jsx';
import PropertyWizard from '../../features/broker/PropertyWizard.jsx';
function PublishedEditor({property,onClose,onSaved}){
  const {api}=useAuth();const action=useAction();const [description,setDescription]=useState(property.description);const [images,setImages]=useState(property.images);
  function upload(event){const files=Array.from(event.target.files??[]);event.target.value='';action.run(async()=>{const uploaded=[];for(const file of files){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new Error('Use JPG, PNG or WEBP images no larger than 5 MB.');uploaded.push(await api.uploads.create(file,'property'));}return uploaded;},media=>setImages(previous=>[...previous,...media]));}
  function save(event){event.preventDefault();action.run(()=>api.properties.update(property._id,{description:description.trim(),images}),onSaved);}
  return <section className="dv-panel dv-admin-editor"><div className="dv-section-heading"><h2>Edit disclosure: {property.title}</h2><button className="dv-button dv-secondary" disabled={action.pending} onClick={onClose}>Close editor</button></div><p className="dv-small">Only the description and images may be changed here. Financial and lifecycle fields remain server-controlled.</p><ErrorNotice error={action.error}/><Form error={action.error} className="dv-form" onSubmit={save}><Field name="description" label="Description"><textarea value={description} onChange={event=>setDescription(event.target.value)} minLength={20} maxLength={10000} required disabled={action.pending}/></Field><Field name="images" label="Add property images" type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={upload} disabled={action.pending}/><div className="dv-media">{images.map((image,index)=><figure key={image.publicId}><img src={image.url} alt={`Property image ${index+1}`}/><figcaption>{image.name}</figcaption><button type="button" className="dv-text" disabled={action.pending} onClick={()=>setImages(previous=>previous.filter((_,position)=>position!==index))}>Remove image {index+1}</button></figure>)}</div><button className="dv-button" disabled={action.pending||images.length<3}>{action.pending?'Saving…':'Save disclosure changes'}</button><p className="dv-small">Keep at least three property images.</p></Form></section>;
}
export default function AdminProperties(){
  const {api,constants,user}=useAuth();const location=useLocation();const [page,setPage]=useState(1);const [filters,setFilters]=useState(()=>{const status=new URLSearchParams(location.search).get('status');return {sort:'-createdAt',...(enumValues(constants.PROPERTY_STATUS).includes(status)?{status}:{})};});
  const resource=useResource(()=>api.admin.properties({page,limit:20,...filters}),[page,filters]);const action=useAction();const [selection,setSelection]=useState(null);const [reason,setReason]=useState('');const [message,setMessage]=useState('');const [create,setCreate]=useState(false);const [editor,setEditor]=useState(null);
  function apply(event){event.preventDefault();setFilters(Object.fromEntries([...new FormData(event.currentTarget)].filter(([,value])=>value.trim())));setPage(1);}
  function select(property,kind){action.setError(null);setReason('');setSelection({property,kind});}
  function execute(){action.run(async()=>{const {property,kind}=selection;if(kind==='approve')return api.properties.approve(property._id);if(kind==='reject'){if(!reason.trim())throw validationError('reason','A rejection reason is required.');return api.properties.reject(property._id,{reason:reason.trim()});}return api.properties.changeStatus(property._id,{status:kind});},result=>{setMessage(selection.kind==='CANCELLED'?`Property cancelled. ${money(result.refundedAmount)} refunded across ${result.refundedInvestments} investments.`:`Property ${selection.kind==='approve'?'approved':selection.kind==='reject'?'rejected':'acquisition recorded'}.`);setSelection(null);resource.reload();});}
  return <Page title="Property management" eyebrow="Review & lifecycle" actions={<button className="dv-button" onClick={()=>{setCreate(previous=>!previous);setEditor(null);}}>{create?'Close new listing':'Create admin listing'}</button>}><ErrorNotice error={action.error}/>{message&&<Notice>{message}</Notice>}{create&&<section className="dv-panel"><h2>Create an administrator listing</h2><PropertyWizard mode="admin" onSaved={()=>resource.reload()} onSubmitted={()=>{setCreate(false);setMessage('Administrator listing submitted for review.');resource.reload();}}/></section>}{editor&&(['DRAFT','REJECTED'].includes(editor.status)?<section className="dv-panel"><div className="dv-section-heading"><h2>Edit administrator draft</h2><button className="dv-button dv-secondary" onClick={()=>setEditor(null)}>Close draft</button></div><PropertyWizard mode="admin" propertyId={editor._id} onSaved={()=>resource.reload()} onSubmitted={()=>{setEditor(null);resource.reload();}}/></section>:<PublishedEditor key={editor._id} property={editor} onClose={()=>setEditor(null)} onSaved={()=>{setEditor(null);setMessage('Property disclosures updated.');resource.reload();}}/>)}
    <Form className="dv-filter-grid dv-panel" onSubmit={apply}><Field label="Search properties" name="search" maxLength={100}/><Field label="Status" name="status"><select defaultValue={filters.status??''}><option value="">All statuses</option>{enumValues(constants.PROPERTY_STATUS).map(value=><option key={value} value={value}>{humanize(value)}</option>)}</select></Field><Field label="City" name="city" maxLength={100}/><Field label="Broker ID" name="brokerId" help="Optional 24-character account ID." pattern="[a-fA-F0-9]{24}"/><Field label="Sort" name="sort"><select defaultValue="-createdAt"><option value="-createdAt">Newest first</option><option value="createdAt">Oldest first</option><option value="title">Title A–Z</option><option value="-unitsSold">Most units funded</option></select></Field><button className="dv-button dv-secondary">Apply property filters</button></Form>
    <ResourceState resource={resource} emptyMessage="No properties match these filters.">{data=><><div className="dv-table-wrap" role="region" aria-label="Property management" tabIndex={0}><table className="dv-table"><thead><tr>{['Property','Broker','Status','Valuation','Funding','Actions'].map(label=><th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{data.items.map(property=><tr key={property._id}><td><Link className="dv-property-name" to={`/properties/${property._id}`}>{property.title||'Untitled draft'}</Link><small>{property.city||'Location not supplied'}</small>{property.rejectionReason&&<p className="dv-small">{property.rejectionReason}</p>}</td><td>{property.brokerId||'Admin-created'}</td><td><Status value={property.status}/></td><td>{money(property.valuation)}</td><td style={{minWidth:220}}><Funding property={property}/></td><td><div className="dv-review-actions">{property.status==='PENDING_APPROVAL'&&<><button className="dv-button" disabled={action.pending} onClick={()=>select(property,'approve')}>Approve</button><button className="dv-button dv-secondary" disabled={action.pending} onClick={()=>select(property,'reject')}>Reject</button></>}{property.status==='FUNDED'&&<button className="dv-button" disabled={action.pending} onClick={()=>select(property,'HOLDING')}>Record acquisition</button>}{property.status==='LIVE'&&<button className="dv-button dv-secondary" disabled={action.pending} onClick={()=>select(property,'CANCELLED')}>Cancel & refund</button>}{property.status==='HOLDING'&&<Link className="dv-button" to={`/admin/properties/${property._id}/sell`}>Record sale</Link>}{(['LIVE','FUNDED','HOLDING'].includes(property.status)||(['DRAFT','REJECTED'].includes(property.status)&&property.createdBy===user._id))&&<button className="dv-button dv-secondary" disabled={action.pending} onClick={()=>{setEditor(property);setCreate(false);}}>Edit {['DRAFT','REJECTED'].includes(property.status)?'draft':'disclosures'}</button>}</div></td></tr>)}</tbody></table></div><Pagination data={data} page={page} onPage={setPage}/></>}</ResourceState><EmptyPagePagination resource={resource} page={page} onPage={setPage}/>
    <Confirm open={!!selection} title={selection?.kind==='CANCELLED'?'Cancel this property and refund investors?':selection?.kind==='HOLDING'?'Record completed acquisition?':selection?.kind==='reject'?'Reject this listing?':'Approve this listing?'} confirmLabel={selection?.kind==='CANCELLED'?'Cancel & refund':selection?.kind==='HOLDING'?'Record acquisition':selection?.kind==='reject'?'Reject listing':'Approve listing'} pending={action.pending} onCancel={()=>setSelection(null)} onConfirm={execute}><p><strong>{selection?.property.title}</strong></p>{selection?.kind==='reject'?<Form error={action.error}><Field name="reason" label="Rejection reason"><textarea value={reason} onChange={event=>setReason(event.target.value)} required maxLength={2000} disabled={action.pending}/></Field></Form>:<p>{selection?.kind==='CANCELLED'?'This terminal action refunds all active investment principal to simulated wallets. It cannot be reversed.':selection?.kind==='HOLDING'?'Confirm that the fully funded property has been acquired. Sale and payout become available after this transition.':'Confirm that the full property details and disclosures have been reviewed. Approval publishes the listing to investors.'}</p>}<ErrorNotice error={action.error}/></Confirm>
  </Page>;
}
