import React, { useState } from 'react';
import useAuth from '../../hooks/useAuth.js';
import { Page, Field, Form, ErrorNotice, Notice, ResourceState, useResource, useAction, Confirm, validationError } from '../auth/DevangUI.jsx';
import '../../components/App.css';
function SettingsForm({settings,onSaved}){
  const {api,features}=useAuth();const action=useAction();const [values,setValues]=useState(Object.fromEntries(Object.entries(settings).map(([key,value])=>[key,String(value)])));const [proposal,setProposal]=useState(null);
  const fields=[['platformFeePct','Platform fee (%)'],['brokerCommissionPct','Broker commission (%)'],['maxOwnershipPct','Platform ownership cap (%)']];
  function review(event){event.preventDefault();action.setError(null);try{const body={};for(const [field]of fields){if(field==='maxOwnershipPct'&&!features.ownershipCap)continue;const value=values[field];if(!/^\d+(\.\d{1,2})?$/.test(value)||Number(value)>100||(field==='maxOwnershipPct'&&Number(value)<=0))throw validationError(field,field==='maxOwnershipPct'?'Enter a rate above 0 and at most 100, with up to 2 decimal places.':'Enter a rate between 0 and 100, with up to 2 decimal places.');body[field]=Number(value);}setProposal(body);}catch(error){action.setError(error);}}
  function save(){action.run(()=>api.admin.updateSettings(proposal),()=>{setProposal(null);onSaved();});}
  return <><ErrorNotice error={action.error}/><Form error={action.error} className="dv-form" onSubmit={review}>{fields.map(([field,label])=><Field key={field} name={field} label={label} inputMode="decimal" value={values[field]} onChange={event=>setValues(previous=>({...previous,[field]:event.target.value}))} required disabled={action.pending||(field==='maxOwnershipPct'&&!features.ownershipCap)} help={field==='maxOwnershipPct'&&!features.ownershipCap?'Ownership cap enforcement is unavailable on this platform.':`Current persisted value: ${settings[field]}%`}/>)}<button className="dv-button" disabled={action.pending}>Review settings changes</button></Form><Confirm open={!!proposal} title="Update platform settings?" confirmLabel="Save settings" pending={action.pending} onCancel={()=>setProposal(null)} onConfirm={save}><dl className="dv-dl">{fields.filter(([field])=>proposal?.[field]!=null).map(([field,label])=><div key={field}><dt>{label}</dt><dd>{settings[field]}% → {proposal[field]}%</dd></div>)}</dl><p style={{marginTop:24}}>These rates apply to future operations. Historical fees, commissions and existing holdings are not recalculated.</p><ErrorNotice error={action.error}/></Confirm></>;
}
export default function AdminSettings(){const {api}=useAuth();const resource=useResource(()=>api.admin.settings());const [saved,setSaved]=useState(false);return <Page title="Platform settings" eyebrow="Fees & eligibility"><p className="dv-portfolio-intro">Settings are stored on the server. New sales validate the current fee against the preview, and rate changes do not alter historical ledger entries.</p>{saved&&<Notice>Platform settings updated.</Notice>}<section className="dv-panel" style={{maxWidth:680}}><ResourceState resource={resource}>{settings=><SettingsForm key={JSON.stringify(settings)} settings={settings} onSaved={()=>{setSaved(true);resource.reload();}}/>}</ResourceState></section></Page>;}
