import React, { useState } from 'react';
import useAuth from '../../hooks/useAuth.js';
import { Page, Field, Form, FeatureGate, ErrorNotice, Notice, ResourceState, useResource, useAction, Confirm, Pagination, Status, enumValues, humanize, validationError } from '../auth/DevangUI.jsx';
import { EmptyPagePagination } from '../../components/AppUI.jsx';
export default function AdminKyc(){
  const {api,features,constants}=useAuth();const [page,setPage]=useState(1);const [status,setStatus]=useState('PENDING');const resource=useResource(()=>api.admin.users({page,limit:10,role:'INVESTOR',kycStatus:status,sort:'createdAt'}),[page,status],!!features.kyc);const action=useAction();const [selection,setSelection]=useState(null);const [reason,setReason]=useState('');const [message,setMessage]=useState('');
  function select(user,review){action.setError(null);setReason('');setSelection({user,review});}
  function execute(){action.run(()=>{if(selection.review==='REJECTED'&&!reason.trim())throw validationError('reason','A rejection reason is required.');return api.admin.reviewKyc(selection.user._id,{status:selection.review,...(selection.review==='REJECTED'?{reason:reason.trim()}:{})});},()=>{setSelection(null);setMessage('Dummy KYC review saved.');resource.reload();});}
  return <Page title="Private dummy KYC reviews" eyebrow="Administrator review queue"><FeatureGate feature="kyc"><Notice warning>Academic review only. Submissions must contain dummy identity files, never real documents.</Notice><ErrorNotice error={action.error}/>{message&&<Notice>{message}</Notice>}<div className="dv-toolbar"><Field label="KYC review status"><select value={status} onChange={event=>{setStatus(event.target.value);setPage(1);}}>{enumValues(constants.KYC_STATUS).map(value=><option key={value} value={value}>{humanize(value)}</option>)}</select></Field></div><ResourceState resource={resource} emptyMessage="No investor accounts in this KYC status.">{data=><>{data.items.map(user=><article className="dv-panel" key={user._id}><div className="dv-section-heading"><div><h2>{user.name}</h2><p className="dv-muted">{user.email}</p></div><Status value={user.kyc.status}/></div>{user.kyc.reason&&<Notice warning>Previous review reason: {user.kyc.reason}</Notice>}<h2>Private dummy documents</h2>{user.kyc.docs?.length?<ul className="dv-document-list">{user.kyc.docs.map(document=><li key={document.publicId}><a className="dv-doc-preview" href={document.url} target="_blank" rel="noreferrer">Open {document.name}</a></li>)}</ul>:<p className="dv-muted">No dummy documents submitted.</p>}{user.kyc.selfie&&<a className="dv-doc-preview" href={user.kyc.selfie.url} target="_blank" rel="noreferrer"><img src={user.kyc.selfie.url} alt={`Dummy selfie for ${user.name}`}/><span>Open dummy selfie</span></a>}{user.kyc.status==='PENDING'&&<div className="dv-actions"><button className="dv-button" disabled={action.pending} onClick={()=>select(user,'APPROVED')}>Approve dummy KYC</button><button className="dv-button dv-secondary" disabled={action.pending} onClick={()=>select(user,'REJECTED')}>Reject with reason</button></div>}</article>)}<Pagination data={data} page={page} onPage={setPage}/></>}</ResourceState><EmptyPagePagination resource={resource} page={page} onPage={setPage}/><Confirm open={!!selection} title={`${selection?.review==='APPROVED'?'Approve':'Reject'} dummy KYC?`} confirmLabel="Save KYC review" pending={action.pending} onCancel={()=>setSelection(null)} onConfirm={execute}><p>Review for <strong>{selection?.user.name}</strong>.</p>{selection?.review==='REJECTED'&&<Form error={action.error}><Field name="reason" label="Rejection reason"><textarea value={reason} onChange={event=>setReason(event.target.value)} required maxLength={2000} disabled={action.pending}/></Field></Form>}<p>This records the persisted review decision and notifies the investor when notifications are enabled.</p><ErrorNotice error={action.error}/></Confirm></FeatureGate></Page>;
}
