/**
 * OwnSquare Single-Source Canonical Constants
 * As defined in CONTRACTS.md
 */

export const ROLES = {
  ADMIN: 'ADMIN',
  BROKER: 'BROKER',
  INVESTOR: 'INVESTOR'
};

export const PROPERTY_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  LIVE: 'LIVE',
  FUNDED: 'FUNDED',
  HOLDING: 'HOLDING',
  SOLD: 'SOLD',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

export const PROPERTY_TYPES = {
  APARTMENT: 'APARTMENT',
  VILLA: 'VILLA',
  COMMERCIAL: 'COMMERCIAL',
  PLOT: 'PLOT',
  WAREHOUSE: 'WAREHOUSE'
};

export const TRANSACTION_TYPES = {
  TOPUP: 'TOPUP',
  INVESTMENT: 'INVESTMENT',
  PAYOUT: 'PAYOUT',
  REFUND: 'REFUND',
  COMMISSION: 'COMMISSION',
  WITHDRAWAL: 'WITHDRAWAL',
  FEE: 'FEE'
};

export const TRANSACTION_DIRECTIONS = {
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT'
};

export const INVESTMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  EXITED: 'EXITED',
  REFUNDED: 'REFUNDED'
};

export const KYC_STATUS = {
  NOT_SUBMITTED: 'NOT_SUBMITTED',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

export const WITHDRAWAL_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

export const ENQUIRY_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED'
};

export const NOTIFICATION_TYPES = {
  PROPERTY_APPROVED: 'PROPERTY_APPROVED',
  PROPERTY_REJECTED: 'PROPERTY_REJECTED',
  FUNDING_COMPLETE: 'FUNDING_COMPLETE',
  PAYOUT_CREDITED: 'PAYOUT_CREDITED',
  KYC_APPROVED: 'KYC_APPROVED',
  KYC_REJECTED: 'KYC_REJECTED',
  WITHDRAWAL_APPROVED: 'WITHDRAWAL_APPROVED',
  WITHDRAWAL_REJECTED: 'WITHDRAWAL_REJECTED',
  ENQUIRY_REPLY: 'ENQUIRY_REPLY'
};
