/**
 * OwnSquare Standard Error Catalog
 * As defined in docs/ERROR_CODES.md and CONTRACTS.md
 */

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  BROKER_NOT_APPROVED: 'BROKER_NOT_APPROVED',
  PROPERTY_IMMUTABLE: 'PROPERTY_IMMUTABLE',
  INVALID_PROPERTY_STATUS: 'INVALID_PROPERTY_STATUS',
  ALREADY_FUNDED: 'ALREADY_FUNDED',
  INSUFFICIENT_UNITS: 'INSUFFICIENT_UNITS',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  OWNERSHIP_LIMIT_EXCEEDED: 'OWNERSHIP_LIMIT_EXCEEDED',
  KYC_REQUIRED: 'KYC_REQUIRED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  ALREADY_SOLD: 'ALREADY_SOLD',
  PREVIEW_STALE: 'PREVIEW_STALE',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  DUPLICATE_PAYMENT: 'DUPLICATE_PAYMENT',
  KYC_ALREADY_SUBMITTED: 'KYC_ALREADY_SUBMITTED',
  INVALID_KYC_STATUS: 'INVALID_KYC_STATUS',
  WITHDRAWAL_ALREADY_PROCESSED: 'WITHDRAWAL_ALREADY_PROCESSED',
  ENQUIRY_UNAVAILABLE: 'ENQUIRY_UNAVAILABLE',
  ENQUIRY_CLOSED: 'ENQUIRY_CLOSED',
  UPLOAD_TOO_LARGE: 'UPLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  RATE_LIMITED: 'RATE_LIMITED',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  CONFLICT: 'CONFLICT',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};
