import React from 'react';
import { Link } from 'react-router-dom';
import useAuth from '../../hooks/useAuth.js';
import { Page, ResourceState, useResource, money } from '../auth/DevangUI.jsx';
import { PropertiesGrid } from '../../components/AppUI.jsx';
export default function Landing() {
  const { api, user } = useAuth();
  const stats = useResource(() => api.platform.stats());
  const featured = useResource(() => api.properties.list({status:'LIVE',page:1,limit:3,sort:'-createdAt'}));
  return <Page title="Property ownership, within reach" eyebrow="OwnSquare · Fractional real estate"><section className="dv-hero"><div><h2>A place in property.<br/>A share in its future.</h2><p>Explore carefully disclosed properties, choose your units and follow your ownership from funding to the final sale.</p><div className="dv-actions"><Link className="dv-button" to="/properties">Explore properties</Link>{!user && <Link className="dv-button dv-secondary" to="/signup">Create your account</Link>}</div></div><aside className="dv-panel dv-money-panel"><p className="dv-kicker">Transparent by design</p><h2>Every unit. Every movement.</h2><p>Whole-unit ownership, clear funding progress and a ledger of every transaction.</p><ResourceState resource={stats}>{data => <dl className="dv-dl"><div><dt>Capital raised</dt><dd>{money(data.totalRaised)}</dd></div><div><dt>Active investors</dt><dd>{data.investorCount}</dd></div></dl>}</ResourceState><p className="dv-small">This academic workspace uses simulated or test payments. Property appreciation is an estimate, never a guaranteed return.</p></aside></section>
    <section className="dv-section"><div className="dv-section-heading"><h2>Open for investment</h2><Link to="/properties">View the marketplace</Link></div><ResourceState resource={featured} emptyMessage="There are no live listings at the moment. Approved properties will appear here.">{data => <PropertiesGrid items={data.items}/>}</ResourceState></section>
    <section className="dv-section"><p className="dv-kicker">How it works</p><h2>A clear path from first unit to final payout</h2><div className="dv-steps-content"><article><strong>01 · DISCOVER</strong><h2>Read the details</h2><p>Review valuation, unit price, location, disclosures and the property's funding progress.</p></article><article><strong>02 · PARTICIPATE</strong><h2>Choose your units</h2><p>Use your simulated wallet balance. Your confirmed purchase records units and ownership together.</p></article><article><strong>03 · FOLLOW</strong><h2>Track the journey</h2><p>Follow funding, acquisition and sale. View the final payout and fees in your portfolio and ledger.</p></article></div></section>
    <section className="dv-section dv-faq"><h2>Before you start</h2>{[['Are payments real?','No. This is an academic project. All payments and withdrawals are simulated or use a test provider.'],['How is ownership calculated?','Ownership is your purchased units divided by the property’s total units. The server validates every purchase and prevents over-funding.'],['Are returns guaranteed?','No. Appreciation is a projection assumption. The recorded sale price can be lower than the original valuation.'],['What if a property is cancelled?','A live property may be cancelled by an administrator. Active investments are refunded to the simulated wallet, with a ledger record.'],['Can I list a property?','Register as a broker. Once an administrator approves your account, create a listing and submit its details for property review.']].map(([question,answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section>
  </Page>;
}
