import React, { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import useAuth from '../../hooks/useAuth.js';
import { Page, Notice, ResourceState, useResource, Pagination, Status, Funding, money, humanize } from '../auth/DevangUI.jsx';
import FundingChart from './FundingChart.jsx';
import EnquiryThreads from './EnquiryThreads.jsx';
export default function BrokerPropertyDetail() {
  const { id } = useParams(); const { api, user } = useAuth(); const [page,setPage] = useState(1);
  const resource = useResource(() => api.properties.detail(id),[id]);
  const ownsProperty = resource.data?.brokerId === user?._id;
  const investors = useResource(() => api.properties.investors(id,{page,limit:20,sort:'-units'}),[id,page],ownsProperty);
  const analytics = useResource(() => api.broker.properties({page:1,limit:1,sort:'-createdAt'}),[id],ownsProperty);
  return <Page title={resource.data?.title || 'Property details'} eyebrow="Listing performance" actions={<Link className="dv-button dv-secondary" to="/broker/properties">All listings</Link>}><ResourceState resource={resource}>{property => ownsProperty ? <>
    <div className="dv-actions" style={{marginBottom:24}}><Status value={property.status}/>{user?.brokerApproved && ['DRAFT','REJECTED'].includes(property.status) && <Link className="dv-button" to={`/broker/properties/${id}/edit`}>Edit listing</Link>}</div>
    {property.rejectionReason && <Notice warning>Administrator feedback: {property.rejectionReason}. Correct the draft and resubmit.</Notice>}{property.status === 'PENDING_APPROVAL' && <Notice warning>This listing is under administrator review. Editing is locked until a decision is made.</Notice>}
    <div className="dv-two-col"><section className="dv-panel"><h2>Property overview</h2><p className="dv-muted">{[property.address,property.city,property.state,property.pincode].filter(Boolean).join(', ') || 'Location not supplied'}</p>{property.images?.length > 0 && <div className="dv-photo-grid">{property.images.map((image,index) => <img key={image.publicId} src={image.url} alt={`Property image ${index+1}: ${image.name}`}/>)}</div>}<p className="dv-property-description">{property.description || 'Description not supplied.'}</p><dl className="dv-dl">{[['Type',humanize(property.type)],['Area',property.areaSqft ? `${property.areaSqft} sq ft` : '—'],['Valuation',money(property.valuation)],['Unit price',money(property.unitPrice)],['Total units',property.totalUnits ?? '—'],['Minimum units',property.minUnits ?? '—'],['Expected appreciation',property.expectedAppreciationPct == null ? '—' : `${property.expectedAppreciationPct}%`],['Rental yield',property.rentalYieldPct == null ? '—' : `${property.rentalYieldPct}%`],['Holding period',property.holdingPeriodMonths ? `${property.holdingPeriodMonths} months` : '—'],['Investors',property.investorCount]].map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{property.documents?.length > 0 && <><h2 style={{marginTop:24}}>Disclosures</h2><ul className="dv-document-list">{property.documents.map(document => <li key={document.publicId}><a href={document.url} target="_blank" rel="noreferrer">{document.name}</a></li>)}</ul></>}</section><aside className="dv-panel"><p className="dv-kicker">Funding progress</p><h2>From listing to funded</h2><Funding property={property}/><ResourceState resource={analytics}>{data => <FundingChart series={data.fundingSeries} propertyId={id}/>}</ResourceState><p className="dv-muted">Expected appreciation is a projection assumption. It does not guarantee returns.</p></aside></div>
    <section className="dv-panel"><h2>Investor participation</h2><p className="dv-muted">Names are masked for privacy. Units and amounts are aggregated by the server.</p><ResourceState resource={investors} emptyMessage="No investor participation has been recorded for this property.">{data => <><div className="dv-table-wrap" role="region" aria-label="Masked investor participation" tabIndex={0}><table className="dv-table"><thead><tr>{['Investor','Units','Invested','Ownership'].map(label => <th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{data.items.map(investor => <tr key={investor.investorId}><td>{investor.displayName}</td><td>{investor.units}</td><td>{money(investor.amount)}</td><td>{investor.ownershipPct.toFixed(2)}%</td></tr>)}</tbody></table></div><Pagination data={data} page={page} onPage={setPage}/></>}</ResourceState></section><section className="dv-panel"><EnquiryThreads propertyId={id}/></section>
  </> : <Notice warning>This property is not part of your broker portfolio. Private analytics and editing are unavailable.</Notice>}</ResourceState></Page>;
}
